name: Node.js CI

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main
      - v*

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Lint (Prettier)
        run: pnpm prettier
      - name: Lint (ESLint)
        run: pnpm lint

  test:
    name: Run tests on ${{ matrix.os }} with Node.js v${{ matrix.node }}
    needs: lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node:
          - 14.x
          - 16.x
          - 18.x
        os:
          - ubuntu-latest

    steps:
      - name: Configure git line-breaks for Windows
        run: git config --global core.autocrlf false
        if: matrix.os == 'windows-latest'
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Test
        run: pnpm test
