name: Node.js CI

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main
      - v*

jobs:
  build:
    name: Run tests on ${{ matrix.os }} with Node.js v${{ matrix.node }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node:
          - 16.x
          - 14.x
          - 12.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Configure git line-breaks for Windows
        run: git config --global core.autocrlf false
        if: matrix.os == 'windows-latest'
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
